### ISSUE TITLE
`Keymap.keyForEach` Error

### ISSUE THREAD

**Issue by pmkap** [ifreund/zig-xkbcommon#1]
The `Keymap.keyForEach` wrapper function is not working:

`error: expected type 'fn(*.wlroots.xkbcommon.Keymap, u32, ?*anyopaque) callconv(.C) void', found 'fn(*.wlroots.xkbcommon.Keymap, u32, *command.map.KeycodeMatches) callconv(.C) void'`

This is my corresponding code: https://github.com/pmkap/river/blob/0baab9b466c62b8b8c57a8b6269440551a1d9d07/river/command/map.zig#L93

For now I use the raw function with a manual cast.

**Comment by ifreund** [comment]
Should be fixed by 0f6eda023e6f52ea001c597fda0a7c3e7a2ccce0, thanks for the report!
