### ISSUE TITLE
Cannot figure out how to use `State.Component`

### ISSUE THREAD

**Issue by pmkap** [ifreund/zig-xkbcommon#2]
E.g. the function `State.modNameIsActive()` takes`Component` as the last argument.
I tried among other things:
`xkb_state.modNameIsActive(xkb.names.mod.ctrl, .mods_depressed)`
`xkb_state.modNameIsActive(xkb.names.mod.ctrl, 1 )`

The equivalent C code would look like this:
`xkb_state_mod_name_is_active(xkb_state, XKB_MOD_NAME_CTRL, XKB_STATE_MODS_DEPRESSED)`

Thanks for you help!

**Comment by ifreund** [comment]
The way past me decided to bind component was like this:
```zig
    pub const Component = enum(c_int) {
        _,
        pub const mods_depressed = 1 << 0;
        pub const mods_latched = 1 << 1;
        pub const mods_locked = 1 << 2;
        pub const mods_effective = 1 << 3;
        pub const layout_depressed = 1 << 4;
        pub const layout_latched = 1 << 5;
        pub const layout_locked = 1 << 6;
        pub const layout_effective = 1 << 7;
        pub const leds = 1 << 8;
    };
```
This is a non-exaustive enum with no enum fields but rather several namespaced constants. To call `modNameIsActive()` one would have to do for example:
```zig
 xkb_state.modNameIsActive(xkb.names.mod.ctrl, @intToEnum(Component, Component.mods_depressed | Component.mods_locked | Component.leds));
```
These bindings should probably be revised to use a packed struct instead, though that requires care to avoid stage1 compiler bugs.

**Comment by pmkap** [comment]
Alright, thank you for the detailed explanation!
